name: "averagePool_test"
op {
  input: "inputs"
  output: "output"
  type: "AveragePool"
  arg {
    name: "order"
    s: "NHWC"
  }
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "count_include_pad"
    i: 0
  }
}
external_output: "output"
