name: "constant_fill_use_provided_shape"
op {
  output: "result"
  name: ""
  type: "ConstantFill"
  arg {
    name: "value"
    f: 3.0
  }
  arg {
    name: "shape"
    ints: 7
    ints: 11
    ints: 13
    ints: 17
  }
}
external_output: "result"
