name: "fbfcpacked_4d"
op {
  input: "input"
  input: "weights"
  input: "bias"
  output: "output"
  name: ""
  type: "FbFCPacked"
  arg {
    name: "axis"
    i: 1
  }
}
external_input: "input"
external_input: "weights"
external_input: "bias"
external_output: "output"
