name: "init"
op {
  output: "tensor_fill_float"
  type: "GivenTensorFill"
  arg {
    name: "shape"
    ints: 2
    ints: 2
  }
  arg {
    name: "values"
    floats: 0.0
    floats: 1.0
    floats: 2.0
    floats: 3.0
  }
}
op {
  output: "tensor_int_fill"
  type: "GivenTensorIntFill"
  arg {
    name: "shape"
    ints: 2
    ints: 2
  }
  arg {
    name: "values"
    ints: 0
    ints: 1
    ints: 2
    ints: 3
  }
}
op {
  output: "tensor_int64_fill"
  type: "GivenTensorInt64Fill"
  arg {
    name: "shape"
    ints: 2
    ints: 2
  }
  arg {
    name: "values"
    ints: 0
    ints: 1
    ints: 2
    ints: 3
  }
}
op {
  output: "tensor_string_to_uint8_fill"
  type: "GivenTensorByteStringToUInt8Fill"
  arg {
    name: "shape"
    ints: 2
    ints: 2
  }
  arg {
    name: "values"
    strings: "\200\201\202\203"
  }
}
