name: "gaussian_fill_use_input_shape"
op {
  input: "inputs_0"
  output: "result"
  name: ""
  type: "GaussianFill"
  arg {
    name: "mean"
    f: 0.0
  }
  arg {
    name: "std"
    f: 1.0
  }
}
external_input: "inputs_0"
external_output: "result"
