name: "init"
op {
  output: "conv_w"
  type: "Int8GivenTensorFill"
  arg {
    name: "shape"
    ints: 1
    ints: 1
    ints: 2
    ints: 2
  }
  arg {
    name: "values"
    s: "\1\1\1\1"
  }
  arg {
    name: "Y_scale"
    f: 2
  }
  arg {
    name: "Y_zero_point"
    i: 10
  }
}
op {
  output: "conv_b"
  type: "Int8GivenIntTensorFill"
  arg {
    name: "shape"
    ints: 1
  }
  arg {
    name: "values"
    ints: 2
  }
  arg {
    name: "Y_scale"
    f: 10
  }
  arg {
    name: "Y_zero_point"
    i: 4
  }
}
