name: "init"
op {
  output: "weights"
  type: "Int8GivenTensorFill"
  arg {
    name: "shape"
    ints: 3
    ints: 5
  }
  arg {
    name: "values"
    s: "\x0\x1\x2\x3\x4\x5\x6\x7\x8\x9\xa\xb\xc\xd\xe"
  }
  arg {
    name: "Y_scale"
    f: 1
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
}
op {
  output: "bias"
  type: "Int8GivenTensorFill"
  arg {
    name: "shape"
    ints: 3
  }
  arg {
    name: "values"
    s: "\x0\x1\x2"
  }
  arg {
    name: "Y_scale"
    f: 1
  }
  arg {
    name: "Y_zero_point"
    i: 0
  }
}
