name: "lpnorm"
op {
  input: "input"
  output: "output"
  name: ""
  type: "LpNorm"
  arg {
    name: "p"
    i: 1
  }
  arg {
    name: "average"
    i: 0
  }
}
external_input: "input"
external_output: "output"
