name: "maxpool_test"
op {
  input: "inputs"
  output: "output"
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 2
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "legacy_pad"
    i: 3
  }
}
external_output: "output"
