name: "prepartitioned_multioip_test"
op {
  input: "mm0_in"
  input: "mm1_in"
  output: "mm_out"
  name: ""
  type: "MatMul"
  arg {
    name: "trans_a"
    i: 0
  }
  arg {
    name: "trans_b"
    i: 0
  }
  device_option {
    node_name: "p1"
  }
}
op {
  input: "mm_out"
  input: "add_in"
  output: "add_out"
  name: ""
  type: "Add"
  arg {
    name: "broadcast"
    i: 0
  }
  device_option {
    node_name: "p2"
  }
}
op {
  input: "mm0_in"
  input: "mm_out"
  output: "mul_out"
  name: ""
  type: "Mul"
  arg {
    name: "broadcast"
    i: 0
  }
  device_option {
    node_name: "p0"
  }
}
op {
  input: "mul_out"
  input: "add_out"
  output: "res"
  name: ""
  type: "Sub"
  arg {
    name: "broadcast"
    i: 0
  }
  device_option {
    node_name: "p0"
  }
}
external_input: "mm0_in"
external_input: "mm1_in"
external_input: "add_in"
external_output: "res"

partition_info {
  name: "p0"
  device_id: 2
}
partition_info {
  name: "p1"
  device_id: 0
  device_id: 1
}
partition_info {
  name: "p2"
  device_id: 2
  backend_options {
    backend_name: "BackendA"
    option {
      key: "opt1"
      val: "val1"
    }
    option {
      key: "opt2"
      val: "val2"
    }
  }
  backend_options {
    backend_name: "BackendB"
    option {
      key: "opt3"
      val: "val3"
    }
  }
}
partition_info {
  name: "unused_p3"
  device_id: 2
}
