name: "rowwise_quantized_sparse_lengths_sum_init_net_test"
op {
  output: "data"
  type: "GivenTensorByteStringToUInt8Fill"
  arg {
    name: "shape"
    ints: 3
    ints: 2
  }
  arg {
    name: "values"
    strings: "\000\377\000\377\000\377"
  }
}
op {
  output: "scales_bias"
  type: "GivenTensorFill"
  arg {
    name: "shape"
    ints: 3
    ints: 2
  }
  arg {
    name: "values"
    floats: 0.00078431389
    floats: 1.0
    floats: 0.0043137260
    floats: 2.3
    floats: 0.0047058817
    floats: 4.5
  }
}
